services:
  php-apache:
    image: docker.io/tenent007963/lekir-php-apache:latest
    ports:
      - "13370:80"
      - "4444:4444"
    restart: unless-stopped
  mysql:
    image: docker.io/tenent007963/lekir-mysql:latest
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "lekir"
    restart: unless-stopped